# SPDX-License-Identifier: Apache-2.0
version: 1
metadata:
  name: default
  description: Default local policy for ravn

actions:
  on_anomaly:
    - log
    - alert
    # - kill # optional

thresholds:
  zscore:
    window_seconds: 60
    sigma: 4.0

rules:
  - name: write_then_exec
    description: Detect write->exec within 5s in same process tree
    type: sequence
    pattern:
      - open_write
      - exec
    window_seconds: 5
    action: alert

  - name: privilege_escalation
    description: Detect setuid/capset/ptrace calls
    type: syscall
    syscalls: [setuid, setresuid, capset, ptrace]
    action: alert


